### ISSUE TITLE
hide or show progressbar window

### ISSUE THREAD

**Issue by chudakM** [AndersonMamede/electron-progressbar#8]
How to hide or show progressbar window? tried to use browserWindow show and hide methods but they doesnt work 

Tried this:
.on('aborted', () => {
      event.preventDefault();
      progressBar.hide()
    })

**Comment by AndersonMamede** [comment]
As per design, the progress bar gets unusable after its completion or abortion (it prevents old listeners/events from firing again). If you need to show another progressbar you have to create it again with `new ProgressBar()`.

---

Actually there are no methods such as _show_ or _hide_ for the progressbar:

- the progressbar window **always becomes visible** when the progressbar is created, which means you should create it only when you want it to be visible;

- after creation you can **manually close** the progressbar window (method `close`) - but **be careful** because the 'aborted' event will be fired if the progressbar is not yet completed;

- and unless you set the option `closeOnComplete` to `false`, the window **automatically closes** when the progressbar is completed;

---

There are two ways a progressbar is considered completed, thus its window will be closed:

1) for **determinate or indeterminate progressbar**: by manually calling [`setCompleted`](https://github.com/AndersonMamede/electron-progressbar#setcompleted);

or

2) **only for determinate progressbar**: when it reaches its maximum value (`maxValue` option, defaults to 100);

---

So:

- to manually close the progressbar after a task is done, just call [`setCompleted`](https://github.com/AndersonMamede/electron-progressbar#setcompleted):
```javascript
progressBar.setCompleted();
```

- if you really want to play with the **progressbar's BrowserWindow instance**:
```javascript
// the BrowserWindow instance:
progressBar._window;

// calling the BrowserWindow's hide method
// PS: it will hide the window but won't abort the progressbar
progressBar._window.hide();

// calling the BrowserWindow's show method
progressBar._window.show();
```

---

I hope this clarifies your question. If you need more information just let me know.

**Comment by chudakM** [comment]
progressBar._window.show(); and  progressBar._window.hide();
that's exactly what I wanted
thx!

**Comment by AndersonMamede** [comment]
Sorry for the delay, I hadn't noticed the last message.

There is an example showing how to show/hide the progress bar using ipc:
[examples/5-show-progress-bar-on-button-click](/AndersonMamede/electron-progressbar/tree/master/examples/5-show-progress-bar-on-button-click)
